-- Together Platform — WP3: Admin-1 verification backend (admin RPCs + audit, D15 all-or-nothing)
-- Migration: 20260708150000_wp3_admin_verification.sql
--
-- Backend foundation for the supply gate (S-ADM-02 verification queue). Every admin action goes
-- through a dedicated RPC that (a) enforces is_admin() [role='admin' AND app_metadata.is_admin,
-- from C4], and (b) writes an audit_log row with an `admin_*` action — the admin is transparent
-- to itself (10-ADMIN-SPEC iron rules).
--
-- Document viewing in S-ADM-02 uses short-lived signed URLs generated by the admin web client
-- via the Storage API (the "Allow admins to view all documents" policy from C4 already gates it) —
-- no extra RPC needed here.
--
-- NOT here (env-coupled → WP2 pg_net wiring): the `verified` change → push-to-professional trigger.

-- ============================================================
-- Schema additions
-- ============================================================
alter table public.professionals
  add column if not exists verification_checklist jsonb;   -- legal evidence the checks were done

alter table public.profiles
  add column if not exists suspended_at timestamptz;       -- for S-ADM-03 (suspend/restore)

create table if not exists public.admin_notes (
  id             uuid primary key default gen_random_uuid(),
  target_user_id uuid not null references public.profiles(id) on delete cascade,
  note           text not null,
  created_by     uuid not null references public.profiles(id),
  created_at     timestamptz not null default now()
);
create index if not exists idx_admin_notes_target on public.admin_notes(target_user_id);

alter table public.admin_notes enable row level security;
drop policy if exists admin_notes_admin_all on public.admin_notes;
create policy admin_notes_admin_all on public.admin_notes
  for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());

-- ============================================================
-- admin_verify_professional — approve a professional (D15: all required docs present)
-- ============================================================
create or replace function public.admin_verify_professional(p_pro_id uuid, p_checklist jsonb)
returns void language plpgsql security definer set search_path = public, pg_temp as $$
declare
  v_user_id uuid;
  v_missing text;
begin
  if not public.is_admin() then
    raise exception 'Admin only';
  end if;

  select user_id into v_user_id from professionals where id = p_pro_id;
  if v_user_id is null then
    raise exception 'Professional not found';
  end if;

  -- D15 all-or-nothing: every required document type must be uploaded.
  select string_agg(req.t, ', ' order by req.t) into v_missing
  from (values ('certificate'), ('criminal_record'), ('id_card')) as req(t)
  where not exists (
    select 1 from document_uploads d
    where d.owner_id = v_user_id and d.doc_type = req.t::document_type
  );
  if v_missing is not null then
    raise exception 'Cannot verify: missing required document(s): %', v_missing;
  end if;

  update professionals
  set verified                = 'verified',
      verified_at             = now(),
      verified_by             = auth.uid(),
      verification_checklist  = p_checklist
  where id = p_pro_id;

  -- Mark the reviewed documents as verified.
  update document_uploads
  set verified = true, verified_by = auth.uid(), verified_at = now()
  where owner_id = v_user_id
    and doc_type in ('certificate', 'criminal_record', 'id_card')
    and verified = false;

  insert into audit_log (user_id, resource, resource_id, action, tier, metadata)
  values (auth.uid(), 'professional', p_pro_id, 'admin_verify', 0, coalesce(p_checklist, '{}'::jsonb));
end;
$$;

-- ============================================================
-- admin_reject_document — reject a single document with a mandatory reason
-- ============================================================
create or replace function public.admin_reject_document(p_doc_id uuid, p_reason text)
returns void language plpgsql security definer set search_path = public, pg_temp as $$
begin
  if not public.is_admin() then
    raise exception 'Admin only';
  end if;
  if p_reason is null or length(trim(p_reason)) = 0 then
    raise exception 'A rejection reason is required';
  end if;

  update document_uploads
  set verified       = false,
      rejection_note = p_reason,
      verified_by    = auth.uid(),
      verified_at    = now()
  where id = p_doc_id;
  if not found then
    raise exception 'Document not found';
  end if;

  insert into audit_log (user_id, resource, resource_id, action, tier, metadata)
  values (auth.uid(), 'document', p_doc_id, 'admin_reject_document', 0,
          jsonb_build_object('reason', p_reason));
end;
$$;

-- ============================================================
-- admin_log_reasoned_view — record a reasoned view of sensitive (TIER-3) data
-- ============================================================
create or replace function public.admin_log_reasoned_view(
  p_resource    text,
  p_resource_id uuid,
  p_reason      text
)
returns void language plpgsql security definer set search_path = public, pg_temp as $$
begin
  if not public.is_admin() then
    raise exception 'Admin only';
  end if;
  if p_reason is null or length(trim(p_reason)) = 0 then
    raise exception 'A reason is required for a reasoned view';
  end if;

  insert into audit_log (user_id, resource, resource_id, action, tier, metadata)
  values (auth.uid(), p_resource, p_resource_id, 'admin_reasoned_view', 3,
          jsonb_build_object('reason', p_reason));
end;
$$;
